// Generated by CoffeeScript 1.12.4
var assertValid, exec, git;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

module.exports = git.addBranch = function(modulePath, branchName) {
  assertValid(modulePath, "string");
  assertValid(branchName, "string");
  return exec.async("git checkout -b " + branchName, {
    cwd: modulePath
  }).then(function() {
    return branchName;
  }).fail(function(error) {
    if (/Switched to a new branch/.test(error.message)) {
      return;
    }
    throw error;
  });
};
