// Generated by CoffeeScript 1.12.4
var assertValid, exec, git, optionTypes;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

optionTypes = {
  force: "boolean?"
};

module.exports = git.addTag = function(modulePath, tagName, options) {
  var args;
  if (options == null) {
    options = {};
  }
  assertValid(modulePath, "string");
  assertValid(tagName, "string");
  assertValid(options, optionTypes);
  args = [tagName];
  if (options.force) {
    args.unshift("-f");
  }
  return exec.async("git tag", args, {
    cwd: modulePath
  }).fail(function(error) {
    var expected;
    if (!options.force) {
      expected = "fatal: tag '" + tagName + "' already exists";
      if (error.message === expected) {
        throw Error("Tag already exists!");
      }
    }
    throw error;
  });
};
