// Generated by CoffeeScript 1.12.4
var assertValid, exec, git, optionTypes;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

optionTypes = {
  lines: "array?"
};

module.exports = git.blame = function(modulePath, filePath, options) {
  var args, lines;
  if (options == null) {
    options = {};
  }
  assertValid(modulePath, "string");
  assertValid(filePath, "string");
  assertValid(options, optionTypes);
  args = ["--porcelain"];
  lines = options.lines;
  if (lines && lines.length >= 2) {
    args.push("-L" + lines[0] + "," + lines[1]);
  }
  args.push("--", filePath);
  return exec.async("git blame", args, {
    cwd: modulePath
  });
};
