// Generated by CoffeeScript 1.12.4
var assertValid, exec, git, optionTypes;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

optionTypes = {
  remote: "string?"
};

module.exports = git.deleteTag = function(modulePath, tagName, options) {
  if (options == null) {
    options = {};
  }
  assertValid(modulePath, "string");
  assertValid(tagName, "string");
  assertValid(options, optionTypes);
  return exec.async("git tag -d " + tagName, {
    cwd: modulePath
  }).then(function() {
    if (!options.remote) {
      return;
    }
    return exec.async("git push " + options.remote + " :" + tagName, {
      cwd: modulePath
    });
  });
};
