// Generated by CoffeeScript 1.12.4
var assertValid, exec, fs, git;

assertValid = require("assertValid");

exec = require("exec");

fs = require("io/sync");

git = require("./core");

module.exports = git.deleteFile = function(modulePath, filePath) {
  var args;
  assertValid(modulePath, "string");
  assertValid(filePath, "string");
  if (fs.isDir(filePath)) {
    args = ["-r", filePath];
  } else {
    args = [filePath];
  }
  return exec.async("git rm", args, {
    cwd: modulePath
  });
};
