// Generated by CoffeeScript 1.12.4
var assertValid, exec, find, git, os;

find = require("finder").find;

assertValid = require("assertValid");

exec = require("exec");

os = require("os");

git = require("./core");

module.exports = git.diff = function(modulePath, firstCommit, lastCommit) {
  if (lastCommit == null) {
    lastCommit = "HEAD";
  }
  assertValid(modulePath, "string");
  assertValid(firstCommit, "string");
  assertValid(lastCommit, "string");
  return exec.async("git diff --raw " + firstCommit + ".." + lastCommit, {
    cwd: modulePath
  }).then(function(stdout) {
    var lines, regex;
    lines = stdout.split(os.EOL);
    regex = /^:[0-9]{6} [0-9]{6} [0-9a-z]{7}\.\.\. [0-9a-z]{7}\.\.\. (.)\t(.+)$/;
    return lines.map(function(line) {
      var path, status;
      status = find(regex, line, 1);
      path = find(regex, line, 2);
      return {
        status: status,
        path: path
      };
    });
  }).fail(function(error) {
    if (/unknown revision or path not in the working tree/.test(error.message)) {
      throw Error("Unknown revision (or path not in the working tree)!");
    }
    throw error;
  });
};
