// Generated by CoffeeScript 1.12.4
var Promise, assertValid, git, semver;

assertValid = require("assertValid");

Promise = require("Promise");

semver = require("node-semver");

require("./getVersions");

git = require("./core");

module.exports = git.findVersion = function(modulePath, versionPattern) {
  assertValid(modulePath, "string");
  assertValid(versionPattern, "string");
  return git.getVersions(modulePath).then(function(versions) {
    var version;
    version = semver.maxSatisfying(versions, versionPattern);
    return Promise.resolve(version, versions);
  });
};
