// Generated by CoffeeScript 1.12.4
var Finder, assertValid, exec, git, isValid, optionTypes, os;

assertValid = require("assertValid");

isValid = require("isValid");

Finder = require("finder");

exec = require("exec");

os = require("os");

require("./getRemotes");

git = require("./core");

optionTypes = {
  raw: "boolean?"
};

module.exports = git.getBranches = function(modulePath, remoteName, options) {
  if (isValid(remoteName, "string")) {
    if (options == null) {
      options = {};
    }
  } else {
    options = remoteName || {};
    remoteName = null;
  }
  assertValid(modulePath, "string");
  assertValid(remoteName, "string|null");
  assertValid(options, optionTypes);
  if (remoteName) {
    return git.getRemotes(modulePath).then(function(remotes) {
      var remoteUri;
      remoteUri = remotes[remoteName].push;
      return exec.async("git ls-remote --heads " + remoteUri, {
        cwd: modulePath
      });
    }).then(function(stdout) {
      var branches, findName, i, len, line, name, ref;
      if (options.raw) {
        return stdout;
      }
      findName = Finder(/refs\/heads\/(.+)$/);
      branches = [];
      ref = stdout.split(os.EOL);
      for (i = 0, len = ref.length; i < len; i++) {
        line = ref[i];
        name = findName(line);
        if (!name) {
          continue;
        }
        branches.push(name);
      }
      return branches;
    });
  }
  return exec.async("git branch", {
    cwd: modulePath
  }).then(function(stdout) {
    var branches, findName, i, len, line, name, ref;
    if (options.raw) {
      return stdout;
    }
    findName = Finder(/^[\*\s]+([a-zA-Z0-9_\-\.]+)$/);
    branches = [];
    ref = stdout.split(os.EOL);
    for (i = 0, len = ref.length; i < len; i++) {
      line = ref[i];
      name = findName(line);
      if (!name) {
        continue;
      }
      branches.push(name);
      if (line[0] === "*") {
        branches.current = name;
      }
    }
    return branches;
  });
};
