// Generated by CoffeeScript 1.12.4
var assertValid, exec, git;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

module.exports = git.getBranch = function(modulePath) {
  assertValid(modulePath, "string");
  return exec.async("git rev-parse --abbrev-ref HEAD", {
    cwd: modulePath
  }).fail(function(error) {
    if (/ambiguous argument 'HEAD'/.test(error.message)) {
      return null;
    }
    throw error;
  });
};
