// Generated by CoffeeScript 1.12.4
var assertValid, exec, git, log;

assertValid = require("assertValid");

exec = require("exec");

log = require("log");

git = require("./core");

module.exports = git.getConfig = function(keyPath) {
  var args;
  assertValid(keyPath, "string?");
  args = keyPath ? ["--get", keyPath] : ["--list"];
  return exec.async("git config", args).then(function(stdout) {
    var config;
    if (keyPath) {
      return stdout;
    }
    config = Object.create(null);
    stdout.split(log.ln).forEach(function(entry) {
      var key, ref, value;
      ref = entry.split("="), key = ref[0], value = ref[1];
      return config[key] = value;
    });
    return config;
  });
};
