// Generated by CoffeeScript 1.12.4
var Promise, assertValid, exec, git, optionTypes;

assertValid = require("assertValid");

Promise = require("Promise");

exec = require("exec");

require("./getBranch");

require("./hasBranch");

git = require("./core");

optionTypes = {
  remote: "string?",
  message: "boolean?"
};

module.exports = git.getHead = function(modulePath, branchName, options) {
  if (options == null) {
    options = {};
  }
  assertValid(modulePath, "string");
  assertValid(branchName, "string?");
  assertValid(options, optionTypes);
  return Promise["try"](function() {
    if (branchName) {
      return git.hasBranch(modulePath, branchName).then(function(hasBranch) {
        if (hasBranch) {
          return;
        }
        return branchName = null;
      });
    }
    return git.getBranch(modulePath).then(function(currentBranch) {
      return branchName = currentBranch;
    });
  }).then(function() {
    var args;
    if (branchName === null) {
      return null;
    }
    args = ["-1", "--pretty=oneline", options.remote ? options.remote + "/" + branchName : branchName];
    return exec.async("git log", args, {
      cwd: modulePath
    }).then(function(stdout) {
      var id, separator;
      separator = stdout.indexOf(" ");
      id = stdout.slice(0, separator);
      if (options.message) {
        return {
          id: id,
          message: stdout.slice(separator + 1)
        };
      }
      return id;
    });
  });
};
