// Generated by CoffeeScript 1.12.4
var assertValid, exec, git, os;

assertValid = require("assertValid");

exec = require("exec");

os = require("os");

git = require("./core");

module.exports = git.getTags = function(modulePath) {
  assertValid(modulePath, "string");
  return exec.async("git tag", {
    cwd: modulePath
  }).then(function(stdout) {
    if (stdout.length === 0) {
      return [];
    }
    return stdout.split(os.EOL);
  });
};
