// Generated by CoffeeScript 1.12.4
var SortedArray, assertValid, git, semver;

SortedArray = require("SortedArray");

assertValid = require("assertValid");

semver = require("node-semver");

require("./getTags");

git = require("./core");

module.exports = git.getVersions = function(modulePath) {
  assertValid(modulePath, "string");
  return git.getTags(modulePath).then(function(tagNames) {
    var i, len, tagName, versions;
    versions = SortedArray([], semver.compare);
    for (i = 0, len = tagNames.length; i < len; i++) {
      tagName = tagNames[i];
      if (!semver.valid(tagName)) {
        continue;
      }
      versions.insert(tagName);
    }
    return versions.array;
  });
};
