// Generated by CoffeeScript 1.12.4
var assertValid, fs, git, path;

assertValid = require("assertValid");

path = require("path");

fs = require("io/sync");

git = require("./core");

module.exports = git.isRepo = function(modulePath) {
  assertValid(modulePath, "string");
  if (modulePath[0] === ".") {
    modulePath = path.resolve(process.cwd(), modulePath);
  } else if (!path.isAbsolute(modulePath)) {
    modulePath = path.resolve(modulePath);
  }
  modulePath = path.join(modulePath, ".git");
  return fs.isDir(modulePath);
};
