// Generated by CoffeeScript 1.12.4
var assertValid, git, hasKeys;

assertValid = require("assertValid");

hasKeys = require("hasKeys");

require("./getStatus");

git = require("./core");

module.exports = git.isStaged = function(modulePath) {
  assertValid(modulePath, "string");
  return git.getStatus(modulePath).then(function(status) {
    return hasKeys(status.staged);
  });
};
