// Generated by CoffeeScript 1.12.4
var Maybe, MergeStrategy, OneOf;

Maybe = require("Maybe");

OneOf = require("OneOf");

MergeStrategy = OneOf("MergeStrategy", ["ours", "theirs"]);

module.exports = MergeStrategy;
