// Generated by CoffeeScript 1.12.4
var MergeStrategy, assertValid, commitTypes, exec, git, isValid, optionTypes, valido;

assertValid = require("assertValid");

isValid = require("isValid");

valido = require("valido");

exec = require("exec");

MergeStrategy = require("./MergeStrategy");

require("./isClean");

git = require("./core");

commitTypes = valido([
  "string", {
    from: "string",
    to: "string"
  }
]);

optionTypes = {
  strategy: [MergeStrategy, "?"]
};

module.exports = git.pick = function(modulePath, commit, options) {
  var args;
  if (options == null) {
    options = {};
  }
  assertValid(modulePath, "string");
  assertValid(commit, commitTypes);
  assertValid(options, optionTypes);
  args = isValid(commit, "object") ? [commit.from + ".." + commit.to] : [commit];
  if (options.strategy) {
    args.push("-X", options.strategy);
  }
  return exec.async("git cherry-pick", args, {
    cwd: modulePath
  }).then(function() {
    return git.isClean(modulePath);
  }).fail(function(error) {
    if (/error: could not apply/.test(error.message)) {
      return true;
    }
    throw error;
  }).then(function(clean) {
    if (clean) {
      return;
    }
    return exec.async("git cherry-pick --continue", {
      cwd: modulePath
    });
  });
};
