// Generated by CoffeeScript 1.12.4
var assertValid, exec, git;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

module.exports = git.popStash = function(modulePath) {
  assertValid(modulePath, "string");
  return exec.async("git stash pop", {
    cwd: modulePath
  });
};
