// Generated by CoffeeScript 1.12.4
var assertValid, exec, git, optionTypes;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

optionTypes = {
  keepIndex: "boolean?",
  includeUntracked: "boolean?"
};

module.exports = git.pushStash = function(modulePath, options) {
  var args;
  if (options == null) {
    options = {};
  }
  assertValid(modulePath, "string");
  assertValid(options, optionTypes);
  args = [];
  if (options.keepIndex) {
    args.push("--keep-index");
  }
  if (options.includeUntracked) {
    args.push("--include-untracked");
  }
  return exec.async("git stash", args, {
    cwd: modulePath
  }).fail(function(error) {
    if (/bad revision 'HEAD'/.test(error.message)) {
      throw Error("Cannot stash unless an initial commit exists!");
    }
    throw error;
  });
};
