// Generated by CoffeeScript 1.12.4
var assertValid, exec, git;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

module.exports = git.renameFile = function(modulePath, oldName, newName) {
  var rootLength;
  assertValid(modulePath, "string");
  assertValid(oldName, "string");
  assertValid(newName, "string");
  rootLength = modulePath.length;
  if (oldName[0] === "/") {
    if (modulePath !== oldName.slice(0, rootLength)) {
      throw Error("'oldName' must be a descendant of 'modulePath'!");
    }
    oldName = oldName.slice(rootLength + 1);
  }
  if (newName[0] === "/") {
    if (modulePath !== newName.slice(0, rootLength)) {
      throw Error("'newName' must be a descendant of 'modulePath'!");
    }
    newName = newName.slice(rootLength + 1);
  }
  return exec.async("git mv", [oldName, newName], {
    cwd: modulePath
  });
};
