// Generated by CoffeeScript 1.12.4
var assertValid, exec, git, isValid, optionTypes;

assertValid = require("assertValid");

isValid = require("isValid");

exec = require("exec");

git = require("./core");

optionTypes = {
  clean: "boolean?"
};

module.exports = git.resetBranch = function(modulePath, commit, options) {
  var hardness;
  if (isValid(commit, "object")) {
    options = commit;
    commit = "HEAD";
  } else {
    if (options == null) {
      options = {};
    }
  }
  assertValid(modulePath, "string");
  assertValid(commit, "string|null");
  assertValid(options, optionTypes);
  if (commit === null) {
    return exec.async("git update-ref -d HEAD", {
      cwd: modulePath
    }).then(function() {
      return options.clean && exec.async("git reset --hard", {
        cwd: modulePath
      });
    });
  } else {
    hardness = options.clean ? "--hard" : "--soft";
    return exec.async("git reset", [hardness, commit], {
      cwd: modulePath
    });
  }
};
