// Generated by CoffeeScript 1.12.4
var assertValid, exec, git, isValid, optionTypes, path, sync;

assertValid = require("assertValid");

isValid = require("isValid");

path = require("path");

exec = require("exec");

sync = require("sync");

git = require("./core");

optionTypes = {
  commit: "string?",
  dryRun: "boolean?"
};

module.exports = git.resetFiles = function(modulePath, files, options) {
  var args;
  if (options == null) {
    options = {};
  }
  assertValid(modulePath, "string");
  assertValid(files, "string|array");
  assertValid(options, optionTypes);
  if (isValid(files, "string")) {
    files = [files];
  } else if (!files.length) {
    return;
  }
  files = sync.map(files, function(filePath) {
    if (filePath[0] === path.sep) {
      filePath = path.relative(modulePath, filePath);
      if (filePath[0] === ".") {
        throw Error("'filePath' must be a descendant of: '" + modulePath + "'");
      }
    }
    return filePath;
  });
  args = [options.commit || "HEAD", "--"].concat(files);
  if (options.dryRun) {
    args.push("-p");
  }
  return exec.async("git checkout", args, {
    cwd: modulePath
  });
};
