// Generated by CoffeeScript 2.3.0
// TODO: Test against existing branch name.
var assertValid, exec, git;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

module.exports = git.addBranch = async function(repo, branch) {
  var err;
  assertValid(repo, "string");
  assertValid(branch, "string");
  try {
    await exec(`git checkout -b ${branch}`, {
      cwd: repo
    });
  } catch (error) {
    err = error;
    if (/Switched to a new branch/.test(err.message)) { // 'git checkout' incorrectly prints to stderr
      return;
    }
    throw err;
  }
};
