// Generated by CoffeeScript 2.3.0
var assertValid, exec, git, optionTypes;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

optionTypes = {
  force: "boolean?"
};

module.exports = git.addTag = async function(repo, tag, opts = {}) {
  var args, err;
  assertValid(repo, "string");
  assertValid(tag, "string");
  assertValid(opts, optionTypes);
  args = [tag];
  if (opts.force) {
    args.push("-f");
  }
  try {
    await exec("git tag", args, {
      cwd: repo
    });
  } catch (error) {
    err = error;
    if (!opts.force) {
      if (err.message === `fatal: tag '${tag}' already exists`) {
        throw Error("Tag already exists!");
      }
    }
    throw err;
  }
};
