// Generated by CoffeeScript 2.3.0
var assertValid, exec, git, optionTypes;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

optionTypes = {
  lines: "array?"
};

module.exports = git.blame = async function(repo, file, opts = {}) {
  var args, lines;
  assertValid(repo, "string");
  assertValid(file, "string");
  assertValid(opts, optionTypes);
  args = ["--porcelain"];
  ({lines} = opts);
  if (lines && lines.length >= 2) {
    args.push("-L" + lines[0] + "," + lines[1]);
  }
  args.push("--", file);
  return (await exec("git blame", args, {
    cwd: repo
  }));
};

// TODO: Parse the output
