// Generated by CoffeeScript 2.3.0
var assertValid, exec, git, optionTypes;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

optionTypes = {
  dest: "string?",
  depth: "number?",
  branch: "string?"
};

module.exports = git.clone = async function(repo, src, opts = {}) {
  var args;
  assertValid(repo, "string");
  assertValid(src, "string");
  assertValid(opts, optionTypes);
  args = [src];
  if (opts.dest) {
    args.push(opts.dest);
  }
  if (opts.branch) {
    args.push("--branch", opts.branch);
  }
  if (opts.depth) {
    args.push("--depth", opts.depth);
  }
  args.push("--quiet");
  await exec("git clone", args, {
    cwd: repo
  });
};
