// Generated by CoffeeScript 2.3.0
var assertValid, exec, git, optionTypes, os;

assertValid = require("assertValid");

exec = require("exec");

os = require("os");

git = require("./core");

optionTypes = {
  remote: "string?",
  remoteOnly: "boolean?"
};

module.exports = git.deleteBranch = async function(repo, branch, opts = {}) {
  var err, expected, lines;
  assertValid(repo, "string");
  assertValid(branch, "string");
  assertValid(opts, optionTypes);
  try {
    if (!opts.remoteOnly) {
      await exec(`git branch -D ${branch}`, {
        cwd: repo
      });
    }
    if (opts.remote) {
      await exec(`git push ${opts.remote} --delete ${branch}`, {
        cwd: repo
      });
    }
  } catch (error) {
    err = error;
    expected = `error: branch '${branch}' not found.`;
    if (err.message === expected) {
      throw Error("The given branch does not exist!");
    }
    expected = `error: Cannot delete the branch '${branch}' which you are currently on.`;
    if (err.message === expected) {
      throw Error("Cannot delete the current branch!");
    }
    lines = err.message.split(os.EOL);
    expected = `fatal: '${branch}' does not appear to be a git repository`;
    if (lines[0] === expected) {
      throw Error("The given remote repository does not exist!");
    }
    throw err;
  }
};
