// Generated by CoffeeScript 2.3.0
var Finder, assertValid, exec, getLocalBranches, getRemoteBranches, git, isValid, optionTypes, os;

assertValid = require("assertValid");

isValid = require("isValid");

Finder = require("finder");

exec = require("exec");

os = require("os");

git = require("./core");

optionTypes = {
  raw: "boolean?",
  remote: "string?"
};

module.exports = git.getBranches = function(repo, opts) {
  assertValid(repo, "string");
  assertValid(opts, optionTypes);
  if (opts.remote) {
    return getRemoteBranches(repo, opts);
  } else {
    return getLocalBranches(repo, opts);
  }
};

getRemoteBranches = async function(repo, opts) {
  var branches, findName, i, len, line, name, ref, stdout;
  stdout = (await exec(`git ls-remote -h ${opts.remote}`, {
    cwd: repo
  }));
  if (opts.raw) {
    return stdout;
  }
  findName = Finder(/refs\/heads\/(.+)$/);
  branches = [];
  ref = stdout.split(os.EOL);
  for (i = 0, len = ref.length; i < len; i++) {
    line = ref[i];
    if (name = findName(line)) {
      branches.push(name);
    }
  }
  return branches;
};

getLocalBranches = async function(repo, opts) {
  var branches, findName, i, len, line, name, ref, stdout;
  stdout = (await exec("git branch", {
    cwd: repo
  }));
  if (opts.raw) {
    return stdout;
  }
  findName = Finder(/^[\*\s]+([a-zA-Z0-9_\-\.]+)$/);
  branches = [];
  ref = stdout.split(os.EOL);
  for (i = 0, len = ref.length; i < len; i++) {
    line = ref[i];
    if (name = findName(line)) {
      branches.push(name);
      if (line[0] === "*") {
        branches.current = name;
      }
    }
  }
  return branches;
};
