// Generated by CoffeeScript 2.3.0
var assertValid, exec, git;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

module.exports = git.getBranch = async function(repo) {
  var err;
  assertValid(repo, "string");
  try {
    return (await exec("git rev-parse --abbrev-ref HEAD", {
      cwd: repo
    }));
  } catch (error) {
    err = error;
    if (/ambiguous argument 'HEAD'/.test(err.message)) {
      return null;
    }
    throw err;
  }
};
