// Generated by CoffeeScript 2.3.0
var assertValid, exec, git, os;

assertValid = require("assertValid");

exec = require("exec");

os = require("os");

git = require("./core");

module.exports = git.getConfig = async function(keyPath) {
  var args, config, stdout;
  assertValid(keyPath, "string?");
  args = keyPath ? ["--get", keyPath] : ["--list"];
  stdout = (await exec("git config", args));
  if (keyPath) {
    return stdout;
  }
  config = Object.create(null);
  stdout.split(os.EOL).forEach(function(entry) {
    var key, value;
    [key, value] = entry.split("=");
    return config[key] = value;
  });
  return config;
};
