// Generated by CoffeeScript 2.3.0
var assertValid, exec, git, optionTypes;

assertValid = require("assertValid");

exec = require("exec");

require("./getBranch");

require("./hasBranch");

git = require("./core");

optionTypes = {
  remote: "string?",
  message: "boolean?"
};

module.exports = git.getHead = async function(repo, branch, opts = {}) {
  var id, separator, stdout;
  assertValid(repo, "string");
  assertValid(branch, "string?");
  assertValid(opts, optionTypes);
  if (!branch) {
    branch = (await git.getBranch(repo));
  } else if (!git.hasBranch(repo, branch)) {
    return null;
  }
  stdout = (await exec("git log", ["-1", "--pretty=oneline", opts.remote ? opts.remote + "/" + branch : branch], {
    cwd: repo
  }));
  separator = stdout.indexOf(" ");
  id = stdout.slice(0, separator);
  if (opts.message) {
    return {
      id,
      message: stdout.slice(separator + 1)
    };
  } else {
    return id;
  }
};
