// Generated by CoffeeScript 2.3.0
var Finder, assertValid, exec, findName, findUri, git, os, regex;

assertValid = require("assertValid");

Finder = require("finder");

exec = require("exec");

os = require("os");

git = require("./core");

regex = /^([^\s]+)\s+([^\s]+)/g;

findName = Finder({
  regex,
  group: 1
});

findUri = Finder({
  regex,
  group: 2
});

module.exports = git.getRemotes = async function(repo) {
  var i, len, line, name, ref, remote, remotes, stdout;
  assertValid(repo, "string");
  remotes = Object.create(null);
  stdout = (await exec("git remote --verbose", {
    cwd: repo
  }));
  if (!stdout.length) {
    return remotes;
  }
  ref = stdout.split(os.EOL);
  for (i = 0, len = ref.length; i < len; i++) {
    line = ref[i];
    name = findName(line);
    remote = remotes[name] || (remotes[name] = {});
    if (/\(push\)$/.test(line)) {
      remote.push = findUri(line);
    } else {
      remote.fetch = findUri(line);
    }
  }
  return remotes;
};
