// Generated by CoffeeScript 2.3.0
// TODO: Add `remote` option
var assertValid, exec, git, optionTypes, os;

assertValid = require("assertValid");

exec = require("exec");

os = require("os");

git = require("./core");

optionTypes = {
  remote: "string?",
  commits: "boolean?"
};

module.exports = git.getTags = async function(repo, opts = {}) {
  var commits, tags;
  assertValid(repo, "string");
  assertValid(opts, optionTypes);
  if (opts.remote) {
    tags = (await exec("git ls-remote -t", opts.remote, {
      cwd: repo
    }));
    return tags.split(os.EOL).map(function(line) {
      var commit, tag;
      [commit, tag] = line.split("\trefs/tags/");
      return opts.commits && {tag, commit} || tag;
    });
  }
  if (tags = (await exec("git tag", {
    cwd: repo
  }))) {
    tags = tags.split(os.EOL);
    if (!opts.commits) {
      return tags;
    }
    commits = (await exec("git rev-list --tags --reverse", {
      cwd: repo
    }));
    commits = commits.split(os.EOL);
    return tags.map(function(tag, i) {
      return {
        tag,
        commit: commits[i]
      };
    });
  }
  return [];
};
