// Generated by CoffeeScript 2.3.0
// TODO: Add `remote` option
var assertValid, exec, git, os;

assertValid = require("assertValid");

exec = require("exec");

os = require("os");

git = require("./core");

module.exports = git.getTags = async function(repo) {
  var stdout;
  assertValid(repo, "string");
  stdout = (await exec("git tag", {
    cwd: repo
  }));
  if (stdout.length) {
    return stdout.split(os.EOL);
  } else {
    return [];
  }
};
