// Generated by CoffeeScript 2.3.0
var SortedArray, assertValid, git, optionTypes, semver;

SortedArray = require("SortedArray");

assertValid = require("assertValid");

semver = require("semver");

require("./getTags");

git = require("./core");

optionTypes = {
  remote: "string?"
};

module.exports = git.getVersions = async function(repo, opts = {}) {
  var i, len, ref, tag, versions;
  assertValid(repo, "string");
  assertValid(opts, optionTypes);
  versions = new SortedArray(semver.compare);
  ref = (await git.getTags(repo, opts));
  for (i = 0, len = ref.length; i < len; i++) {
    tag = ref[i];
    if (semver.valid(tag)) {
      versions.insert(tag);
    }
  }
  return versions.array;
};
