// Generated by CoffeeScript 2.3.0
var SortedArray, assertValid, git, semver;

SortedArray = require("SortedArray");

assertValid = require("assertValid");

semver = require("semver");

require("./getTags");

git = require("./core");

module.exports = git.getVersions = async function(repo) {
  var i, len, ref, tag, versions;
  assertValid(repo, "string");
  versions = new SortedArray(semver.compare);
  ref = (await git.getTags(repo));
  for (i = 0, len = ref.length; i < len; i++) {
    tag = ref[i];
    if (semver.valid(tag)) {
      versions.insert(tag);
    }
  }
  return versions.array;
};
