// Generated by CoffeeScript 2.3.0
var assertValid, git, optionTypes;

assertValid = require("assertValid");

require("./getBranches");

git = require("./core");

optionTypes = {
  remote: "string?"
};

module.exports = git.hasBranch = async function(repo, branch, opts = {}) {
  var branches;
  assertValid(repo, "string");
  assertValid(branch, "string");
  assertValid(opts, optionTypes);
  branches = (await git.getBranches(repo, opts.remote));
  return branches.includes(branch);
};
