// Generated by CoffeeScript 2.3.0
module.exports = require("./core");

require("./addBranch");

require("./addTag");

require("./blame");

require("./commit");

require("./deleteBranch");

require("./deleteTag");

require("./diff");

require("./getBranch");

require("./getBranches");

require("./getConfig");

require("./getHead");

require("./getRemotes");

require("./getStatus");

require("./getTags");

require("./getVersions");

require("./hasBranch");

require("./isClean");

require("./isStaged");

require("./mergeBranch");

require("./pick");

require("./popStash");

require("./pushBranch");

require("./pushStash");

require("./pushTag");

require("./pushTags");

require("./removeFiles");

require("./renameFile");

require("./resetBranch");

require("./revertFiles");

require("./revertHead");

require("./setBranch");

require("./stageFiles");

require("./unstageFiles");
