// Generated by CoffeeScript 2.3.0
var assertValid, git;

assertValid = require("assertValid");

require("./getStatus");

git = require("./core");

module.exports = git.isClean = async function(repo) {
  var status;
  assertValid(repo, "string");
  status = (await git.getStatus(repo, {
    raw: true
  }));
  return status.length === 0;
};
