// Generated by CoffeeScript 2.3.0
var assertValid, git, hasKeys;

assertValid = require("assertValid");

hasKeys = require("hasKeys");

require("./getStatus");

git = require("./core");

module.exports = git.isStaged = async function(repo) {
  assertValid(repo, "string");
  return hasKeys(((await git.getStatus(repo))).staged);
};
