// Generated by CoffeeScript 2.3.0
var valido, values;

valido = require("valido");

values = ["ours", "theirs"];

module.exports = valido({
  test: function(value) {
    return values.includes(value);
  },
  error: function() {
    return Error("Invalid merge strategy");
  }
});
