// Generated by CoffeeScript 2.3.0
var assertValid, exec, git;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

module.exports = git.popStash = async function(repo) {
  assertValid(repo, "string");
  await exec("git stash pop", {
    cwd: repo
  });
};
