// Generated by CoffeeScript 2.3.0
var assertValid, exec, git, optionTypes;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

optionTypes = {
  keepStaged: "boolean?",
  keepUntracked: "boolean?"
};

module.exports = git.pushStash = async function(repo, opts = {}) {
  var args, err;
  assertValid(repo, "string");
  assertValid(opts, optionTypes);
  args = [];
  if (opts.keepStaged) {
    args.push("--keep-index");
  }
  if (!opts.keepUntracked) {
    args.push("--include-untracked");
  }
  try {
    await exec("git stash", args, {
      cwd: repo
    });
  } catch (error) {
    err = error;
    if (/bad revision 'HEAD'/.test(err.message)) {
      throw Error("Cannot stash unless an initial commit exists!");
    }
    throw err;
  }
};
