// Generated by CoffeeScript 2.3.0
// TODO: Add `tags` option or argument
var assertValid, exec, git, optionTypes, os;

assertValid = require("assertValid");

exec = require("exec");

os = require("os");

git = require("./core");

optionTypes = {
  force: "boolean?",
  remote: "string?"
};

module.exports = git.pushTags = async function(repo, opts = {}) {
  var args, err, lines;
  assertValid(repo, "string");
  assertValid(opts, optionTypes);
  args = [opts.remote || "origin", "--tags"];
  if (opts.force) {
    args.push("-f");
  }
  try {
    await exec("git push", args, {
      cwd: repo
    });
  } catch (error) {
    err = error;
    lines = err.message.split(os.EOL);
    if (/\(already exists\)$/.test(lines[1])) {
      throw Error("Tag already exists!");
    }
    if (/\(forced update\)$/.test(lines[1])) {
      return;
    }
    if (/\* \[new tag\]/.test(lines[1])) {
      return;
    }
    throw err;
  }
};
