// Generated by CoffeeScript 2.3.0
// TODO: Test with `file` being a non-existing file.
var assertValid, exec, git, optionTypes;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

optionTypes = {
  cached: "boolean?",
  recursive: "boolean?"
};

module.exports = git.removeFiles = async function(repo, files, opts = {}) {
  var args;
  assertValid(repo, "string");
  assertValid(files, "string|array");
  assertValid(opts, optionTypes);
  args = [];
  if (opts.recursive) {
    args.push("-r");
  }
  if (opts.cached) {
    args.push("--cached");
  }
  await exec("git rm", args, "--", files, {
    cwd: repo
  });
};
