// Generated by CoffeeScript 2.3.0
// TODO: Test with `oldName` not existing.
var assertValid, exec, git, makeRelative, path;

assertValid = require("assertValid");

path = require("path");

exec = require("exec");

git = require("./core");

module.exports = git.renameFile = async function(repo, oldName, newName) {
  assertValid(repo, "string");
  assertValid(oldName, "string");
  assertValid(newName, "string");
  await exec("git mv", makeRelative(oldName), makeRelative(newName), {
    cwd: repo
  });
};

makeRelative = function(repo, file) {
  var name;
  if (!path.isAbsolute(file)) {
    return file;
  }
  name = path.relative(repo, file);
  if (name[0] !== ".") {
    return name;
  }
  throw Error(`Absolute path '${file}' cannot be outside '${repo}'`);
};
