// Generated by CoffeeScript 2.3.0
var assertValid, exec, git, optionTypes, path;

assertValid = require("assertValid");

path = require("path");

exec = require("exec");

git = require("./core");

optionTypes = {
  commit: "string?",
  dryRun: "boolean?"
};

module.exports = git.revertFiles = async function(repo, files, opts = {}) {
  var args;
  assertValid(repo, "string");
  assertValid(files, "string|array");
  assertValid(opts, optionTypes);
  if (typeof files === "string") {
    files = [files];
  } else if (!files.length) {
    return;
  }
  files = files.map(function(file) {
    var name;
    if (!path.isAbsolute(file)) {
      return file;
    }
    name = path.relative(repo, file);
    if (name[0] !== ".") {
      return name;
    }
    throw Error(`Absolute path '${file}' cannot be outside '${repo}'`);
  });
  args = [opts.commit || "HEAD"];
  if (opts.dryRun) {
    args.push("-p");
  }
  // TODO: Possibly parse the 'dryRun' output?
  return (await exec("git checkout", args, "--", files, {
    cwd: repo
  }));
};
