// Generated by CoffeeScript 2.3.0
var git;

require("./resetBranch");

git = require("./core");

module.exports = git.revertHead = async function(repo) {
  var err;
  try {
    await git.resetBranch(repo, "HEAD^", {
      mode: "soft" // TODO: return the new HEAD commit?
    });
  } catch (error) {
    err = error;
    // Undo the initial commit if necessary.
    if (/^fatal: ambiguous argument/.test(err.message)) {
      return git.resetBranch(repo, null, {
        mode: "soft"
      });
    }
    throw err;
  }
};
