// Generated by CoffeeScript 2.3.0
var assertValid, exec, git;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

module.exports = git.stageFiles = async function(repo, files) {
  var err;
  assertValid(repo, "string");
  assertValid(files, "string|array");
  if (typeof files === "string") {
    files = [files];
  } else if (!files.length) {
    return;
  }
  try {
    await exec("git add --", files, {
      cwd: repo
    });
  } catch (error) {
    err = error;
    if (/The following paths are ignored/.test(err.message)) { // 'git add' complains when ignored files are added (eg: 'git add *').
      return;
    }
    throw err;
  }
};
