// Generated by CoffeeScript 2.3.0
var assertValid, exec, git;

assertValid = require("assertValid");

exec = require("exec");

git = require("./core");

module.exports = git.unstageFiles = async function(repo, files) {
  assertValid(repo, "string");
  assertValid(files, "string|array");
  if (typeof files === "string") {
    files = [files];
  } else if (!files.length) {
    return;
  }
  await exec("git reset --", files, {
    cwd: repo
  });
};
